---@param colors flexoki.ThemeColors The color palette to use for highlighting groups
---@param config flexoki.Config The user configuration
---@return flexoki.HighlightGroups # Highlight groups for Neovim
return function(colors, config)
    ---Define neovim default groups
    ---@type flexoki.HighlightGroups
    local groups = {
        -- Editor highlights (:help highlight-groups)
        ColorColumn = { bg = colors.bg2 },
        Conceal = { fg = colors.tx3 },
        CurSearch = { fg = colors.bg, bg = colors.yellow },
        Cursor = { fg = colors.bg, bg = colors.tx },
        lCursor = { link = "Cursor" },
        CursorIM = { link = "Cursor" },
        CursorColumn = { link = "CursorLine" },
        CursorLine = { bg = colors.bg2 },
        Directory = { fg = colors.blue },
        DiffAdd = { fg = colors.green, bg = colors.bg2 },
        DiffChange = { fg = colors.yellow, bg = colors.bg2 },
        DiffDelete = { fg = colors.red, bg = colors.bg2 },
        DiffText = { fg = colors.tx, bg = colors.ui2 },
        EndOfBuffer = { link = "NonText" },
        TermCursor = { link = "Cursor" },
        ErrorMsg = { fg = colors.red },
        WinSeparator = { fg = colors.ui, bg = colors.bg },
        Folded = { fg = colors.tx3, bg = colors.bg2 },
        FoldColumn = { link = "SignColumn" },
        SignColumn = { fg = colors.tx3, bg = colors.bg },
        IncSearch = { link = "CurSearch" },
        Substitute = { link = "Search" },
        LineNr = { fg = colors.tx3 },
        LineNrAbove = { link = "LineNr" },
        LineNrBelow = { link = "LineNr" },
        CursorLineNr = { bold = true },
        CursorLineFold = { link = "FoldColumn" },
        CursorLineSign = { link = "SignColumn" },
        MatchParen = { fg = colors.yellow, bold = true },
        ModeMsg = { fg = colors.tx2 },
        MsgArea = {},
        MsgSeparator = { link = "StatusLine" },
        MoreMsg = { link = "Normal" },
        NonText = { fg = colors.tx3 },
        Normal = { fg = colors.tx, bg = colors.bg },
        NormalFloat = { fg = colors.tx, bg = colors.bg2 },
        FloatBorder = { fg = colors.ui, bg = colors.bg2 },
        FloatTitle = { fg = colors.tx2, bg = colors.bg2 },
        FloatFooter = { link = "FloatTitle" },
        NormalNC = {},
        Pmenu = { fg = colors.tx2, bg = colors.bg2 },
        PmenuSel = { fg = colors.tx2, bg = colors.ui },
        PmenuKind = { link = "Pmenu" },
        PmenuKindSel = { link = "PmenuSel" },
        PmenuExtra = { link = "Pmenu" },
        PmenuExtraSel = { link = "PmenuSel" },
        PmenuSbar = { link = "Pmenu" },
        PmenuThumb = { bg = colors.tx3 },
        PmenuMatch = { bold = true },
        PmenuMatchSelect = { link = "PmenuMatch" },
        ComplMatchIns = {},
        Question = { fg = colors.cyan },
        QuickFixLine = { fg = colors.cyan },
        Search = { fg = colors.tx, bg = colors.yellow3 },
        SnippetTabstop = { link = "Visual" },
        SpecialKey = { fg = colors.tx3 },
        SpellBad = { sp = colors.red, undercurl = true },
        SpellCap = { sp = colors.yellow, undercurl = true },
        SpellLocal = { sp = colors.cyan, undercurl = true },
        SpellRare = { sp = colors.purple, undercurl = true },
        StatusLine = { fg = colors.tx, bg = colors.ui },
        StatusLineNC = { fg = colors.tx3, bg = colors.ui },
        StatusLineTerm = { link = "StatusLine" },
        StatusLineTermNC = { link = "StatusLineNC" },
        TabLine = { link = "StatusLineNC" },
        TabLineFill = { link = "TabLine" },
        TabLineSel = { bold = true },
        Title = { fg = colors.tx, bold = true },
        Visual = { bg = colors.ui2 },
        VisualNOS = { link = "Visual" },
        WarningMsg = { fg = colors.orange },
        Whitespace = { link = "NonText" },
        WildMenu = { link = "PmenuSel" },
        WinBar = { link = "StatusLine" },
        WinBarNC = { link = "StatusLineNC" },

        -- Syntax highlights (:help group-name)
        Comment = { fg = colors.tx3 },
        Constant = { fg = colors.yellow },
        String = { fg = colors.cyan },
        Character = { fg = colors.orange },
        Number = { fg = colors.purple },
        Boolean = { link = "Constant" },
        Float = { link = "Number" },
        Identifier = { fg = colors.blue },
        Function = { fg = colors.orange },
        Statement = { link = "Keyword" },
        Conditional = { link = "Keyword" },
        Repeat = { link = "Keyword" },
        Label = { link = "Keyword" },
        Operator = { fg = colors.tx2 },
        Keyword = { fg = colors.green },
        Exception = { link = "Keyword" },
        PreProc = { fg = colors.orange },
        Include = { link = "PreProc" },
        Define = { link = "PreProc" },
        Macro = { link = "PreProc" },
        PreCondit = { link = "PreProc" },
        Type = { fg = colors.green },
        StorageClass = { link = "Type" },
        Structure = { link = "Type" },
        Typedef = { link = "Type" },
        Special = { fg = colors.red },
        SpecialChar = { link = "Special" },
        Tag = { link = "Special" },
        Delimiter = { link = "Special" },
        SpecialComment = { link = "Special" },
        Debug = { link = "Special" },
        Underlined = { underline = true },
        Ignore = { fg = colors.tx3 },
        Error = { fg = colors.red },
        Todo = { fg = colors.cyan, bold = true },
        Added = { fg = colors.green },
        Changed = { fg = colors.yellow },
        Removed = { fg = colors.red },

        -- Diagnostic highlights (:help diagnostic-highlights)
        DiagnosticError = { fg = colors.red },
        DiagnosticWarn = { fg = colors.orange },
        DiagnosticInfo = { fg = colors.blue },
        DiagnosticHint = { fg = colors.cyan },
        DiagnosticOk = { fg = colors.green },
        DiagnosticVirtualTextError = { link = "DiagnosticError" },
        DiagnosticVirtualTextWarn = { link = "DiagnosticWarn" },
        DiagnosticVirtualTextInfo = { link = "DiagnosticInfo" },
        DiagnosticVirtualTextHint = { link = "DiagnosticHint" },
        DiagnosticVirtualTextOk = { link = "DiagnosticOk" },
        DiagnosticUnderlineError = { sp = colors.red, undercurl = true },
        DiagnosticUnderlineWarn = { sp = colors.orange, undercurl = true },
        DiagnosticUnderlineInfo = { sp = colors.blue, undercurl = true },
        DiagnosticUnderlineHint = { sp = colors.cyan, undercurl = true },
        DiagnosticUnderlineOk = { sp = colors.green, undercurl = true },
        DiagnosticFloatingError = { link = "DiagnosticError" },
        DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
        DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
        DiagnosticFloatingHint = { link = "DiagnosticHint" },
        DiagnosticFloatingOk = { link = "DiagnosticOk" },
        DiagnosticSignError = { link = "DiagnosticError" },
        DiagnosticSignWarn = { link = "DiagnosticWarn" },
        DiagnosticSignInfo = { link = "DiagnosticInfo" },
        DiagnosticSignHint = { link = "DiagnosticHint" },
        DiagnosticSignOk = { link = "DiagnosticOk" },
        DiagnosticDeprecated = { sp = colors.red, strikethrough = true },
        DiagnosticUnnecessary = { link = "Comment" },

        --
        -- Treesitter highlights
        --
        -- Common
        ["@comment"] = { link = "Comment" },
        ["@error"] = { link = "Error" },
        ["@none"] = { bg = "NONE", fg = "NONE" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@operator"] = { link = "Operator" },

        -- Punctuation
        ["@punctuation.bracket"] = { fg = colors.tx2 },
        ["@punctuation.delimiter"] = { fg = colors.tx2 },
        ["@punctuation.special"] = { fg = colors.tx2 },

        -- Literals
        ["@string"] = { link = "String" },
        ["@string.escape"] = { fg = colors.orange },
        ["@string.special"] = { fg = colors.orange },
        ["@string.regex"] = { fg = colors.orange },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { fg = colors.orange },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@float"] = { link = "Float" },

        -- Functions
        ["@function"] = { link = "Function" },
        ["@function.call"] = { fg = colors.orange },
        ["@function.builtin"] = { fg = colors.orange },
        ["@function.macro"] = { fg = colors.magenta },
        ["@method"] = { fg = colors.orange },
        ["@method.call"] = { fg = colors.orange },
        ["@constructor"] = { fg = colors.orange },
        ["@parameter"] = { fg = colors.blue },

        -- Keywords
        ["@keyword"] = { link = "Keyword" },
        ["@keyword.function"] = { fg = colors.green },
        ["@keyword.return"] = { fg = colors.green },
        ["@keyword.operator"] = { fg = colors.green },
        ["@keyword.import"] = { fg = colors.red },
        ["@keyword.directive.preprocessor"] = { fg = colors.magenta },
        ["@keyword.directive"] = { fg = colors.magenta },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.conditional.ternary"] = { fg = colors.green },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.debug"] = { fg = colors.magenta },
        ["@keyword.exception"] = { link = "Exception" },

        -- Types
        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { fg = colors.yellow },
        ["@type.definition"] = { fg = colors.yellow },
        ["@type.qualifier"] = { fg = colors.green },
        ["@type.annotation"] = { fg = colors.blue },
        ["@attribute"] = { fg = colors.blue },
        ["@property"] = { fg = colors.blue },

        -- Identifiers
        ["@variable"] = { fg = colors.blue },
        ["@variable.builtin"] = { fg = colors.magenta },
        ["@constant"] = { fg = colors.yellow },
        ["@constant.builtin"] = { fg = colors.purple },
        ["@constant.macro"] = { fg = colors.magenta },
        ["@namespace"] = { fg = colors.blue },
        ["@symbol"] = { fg = colors.purple },

        -- Text
        ["@text"] = { fg = colors.tx },
        ["@text.strong"] = { fg = colors.tx, bold = true },
        ["@text.emphasis"] = { fg = colors.tx, italic = true },
        ["@text.underline"] = { fg = colors.tx, underline = true },
        ["@text.strike"] = { fg = colors.tx, strikethrough = true },
        ["@text.title"] = { link = "Title" },
        ["@text.literal"] = { fg = colors.cyan },
        ["@text.uri"] = { fg = colors.cyan, underline = true },
        ["@text.math"] = { fg = colors.purple },
        ["@text.environment"] = { fg = colors.orange },
        ["@text.environment.name"] = { fg = colors.yellow },
        ["@text.reference"] = { fg = colors.cyan },
        ["@text.todo"] = { fg = colors.yellow, bold = true },
        ["@text.todo.checked"] = { fg = colors.green },
        ["@text.todo.unchecked"] = { fg = colors.yellow },
        ["@text.note"] = { fg = colors.blue, bold = true },
        ["@text.warning"] = { fg = colors.orange, bold = true },
        ["@text.danger"] = { fg = colors.red, bold = true },
        ["@text.diff.add"] = { link = "DiffAdd" },
        ["@text.diff.delete"] = { link = "DiffDelete" },

        --
        -- LSP semantic token highlights
        --
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.interface"] = { fg = colors.yellow },
        ["@lsp.type.keyword"] = { link = "@keyword" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.variable"] = { link = "@variable" },
        ["@lsp.type.macro"] = { link = "@function.macro" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.number"] = { link = "@number" },
        ["@lsp.type.operator"] = { link = "@operator" },
        ["@lsp.type.string"] = { link = "@string" },
        ["@lsp.type.struct"] = { link = "@structure" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.decorator"] = { link = "@attribute" },
        ["@lsp.type.builtinType"] = { link = "@type.builtin" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.class"] = { link = "@type" },
    }

    -- Add plugin-specific groups
    for _, plugin in ipairs(config.plugins) do
        local plugin_groups = require("flexoki.groups." .. plugin)(colors)
        groups = vim.tbl_extend("force", groups, plugin_groups)
    end

    return groups
end
